server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: huuthang
    url: jdbc:mysql://localhost:3306/wedding_db
    username: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 0
      location: /tmp
twilio:
  account_sid: AC0b34ce3d996ee5c31d9addf80af6b1110
  auth_token: f8dbacdf48f3c009a70bb7eb105ec844d
  trial_number: +132593928665

vnpay:
  returnUrl: http://localhost:8080/api/v1/payment/vnpay-return
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmnCode": QYBSTFGY
  hashSecret: ZZFKYHJMITRTSDOUEIJUFQYRLLRMMSVN
  version: 2.1.0


