server:
    port: 8080
    servlet:
        context-path: /

spring:
    application:
        name: backend
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Huuthang3001
        url: jdbc:mysql://weddingdb.cdysm68wgj3j.us-east-1.rds.amazonaws.com/wedding_db
        username: admin
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    main:
        allow-circular-references: true

    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
            enabled: true
            file-size-threshold: 0
            location: /tmp
    elasticsearch:
        uris: http://localhost:9200

twilio:
    account_sid: AC0b34ce3d996ee5c31d9addf80af6b110
    auth_token: f8dbacdf48f3c009a70bb7eb105ec84d
    trial_number: +13259392865

vnpay:
    returnUrl: https://sweetdream-gjdaath6dchyfwhp.eastus-01.azurewebsites.net/api/v1/payment/vnpay-return
    paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: QYBSTFGY
    hashSecret: ZZFKYHJMITRTSDOUEIJUFQYRLLRMMSVN
    version: 2.1.0
